[tool.poetry]
name = "arcanumbot"
version = "1.1.2"
description = ""
authors = ["StarrFox <starrfox6312@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
aiosqlite = "^0.17.0"
jishaku = "^2.5.1"
pendulum = "^2.1.2"
numpy = "^1.23.2"
reusables = "^0.9.6"
discord-ext-menus = {git = "https://github.com/Rapptz/discord-ext-menus"}
humanize = "^4.3.0"
"discord.py" = "^2.0.1"
psutil = "^5.9.1"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
arcanumbot = "arcanumbot.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
