[tool.poetry]
name = "arcanumbot"
version = "2.0.0"
description = ""
authors = ["StarrFox <starrfox6312@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
aiosqlite = "^0.19.0"
jishaku = "^2.5.1"
pendulum = "^2.1.2"
numpy = "^1.24.3"
discord-ext-menus = {git = "https://github.com/Rapptz/discord-ext-menus"}
humanize = "^4.6.0"
"discord.py" = "^2.2.3"
psutil = "^5.9.5"
click = "^8.1.3"

[tool.poetry.scripts]
arcanumbot = "arcanumbot.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
